Repository spotify/scio, pull requests merged in 2020-11, with the labels that each got.

#3490 Fix getRecord should not throw on a missing field
  scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/syntax/TableRowSyntax.scala
  scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/TableRowSyntaxTest.scala
Labels: bug

#3489 Fix scio version warning in tests
  build.sbt
  scio-core/src/main/scala/com/spotify/scio/VersionUtil.scala
  scio-test/src/test/scala/com/spotify/scio/VersionUtilTest.scala
Labels: bug

#3491 Update mysql-socket-factory to 1.2.0
  build.sbt
Labels: dependency-update

#3454 Rework `com.spotify.scio.transforms` package
  scio-core/src/main/scala/com/spotify/scio/transforms/JavaAsyncConverters.scala
  scio-core/src/main/scala/com/spotify/scio/transforms/ParallelismDoFns.scala
  scio-core/src/main/scala/com/spotify/scio/transforms/WithResourceDoFns.scala
  scio-core/src/main/scala/com/spotify/scio/transforms/package.scala
  scio-core/src/main/scala/com/spotify/scio/transforms/syntax/AllSyntax.scala
  scio-core/src/main/scala/com/spotify/scio/transforms/syntax/SCollectionFileDownloadSyntax.scala
  scio-core/src/main/scala/com/spotify/scio/transforms/syntax/SCollectionParallelismSyntax.scala
  scio-core/src/main/scala/com/spotify/scio/transforms/syntax/SCollectionPipeSyntax.scala.scala
  scio-core/src/main/scala/com/spotify/scio/transforms/syntax/SCollectionSafeSyntax.scala
  scio-core/src/main/scala/com/spotify/scio/transforms/syntax/SCollectionWithResourceSyntax.scala
  scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigtable/BigtableDoFnTest.scala
  scio-test/src/test/scala/com/spotify/scio/transforms/AsyncLookupDoFnTest.scala
Labels: refactoring
