Repository spotify/scio, pull requests merged in 2021-03, with the labels that each got.

#3651 Only allow accesor methods for BigQuery fields in case classes
  scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/MacroUtil.scala
  scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/types/ConverterProviderSpec.scala
  scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/types/ConverterProviderTest.scala
  scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/types/SchemaProviderTest.scala
  scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/types/Schemas.scala
Labels: bug

#3684 Update magnolify-avro, magnolify-bigtable, ... to 0.4.3
  build.sbt
Labels: dependency-update

#3685 Remove unused context bounds, coders and @unused
  scio-avro/src/main/scala/com/spotify/scio/avro/AvroIO.scala
  scio-avro/src/main/scala/com/spotify/scio/avro/syntax/ScioContextSyntax.scala
  scio-avro/src/main/scala/com/spotify/scio/avro/taps.scala
  scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
  scio-core/src/main/scala/com/spotify/scio/estimators/ApproxDistinctCounter.scala
  scio-core/src/main/scala/com/spotify/scio/hash/ApproxFilter.scala
  scio-core/src/main/scala/com/spotify/scio/io/InMemorySink.scala
  scio-core/src/main/scala/com/spotify/scio/io/ScioIO.scala
  scio-core/src/main/scala/com/spotify/scio/schemas/Schema.scala
  scio-core/src/main/scala/com/spotify/scio/values/PairHashSCollectionFunctions.scala
  scio-core/src/main/scala/com/spotify/scio/values/SCollectionWithHotKeyFanout.scala
  scio-examples/src/main/scala/com/spotify/scio/examples/extra/AvroExample.scala
  scio-examples/src/main/scala/com/spotify/scio/examples/extra/MagnolifyAvroExample.scala
  scio-extra/src/main/scala/com/spotify/scio/extra/Breeze.scala
  scio-extra/src/main/scala/com/spotify/scio/extra/csv/CsvIO.scala
  scio-extra/src/main/scala/com/spotify/scio/extra/hll/sketching/SketchHllPlusPlus.scala
  scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala
  scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/syntax/ScioContextSyntax.scala
  scio-repl/src/main/scala/com/spotify/scio/repl/IoCommands.scala
  scio-repl/src/main/scala/com/spotify/scio/repl/package.scala
  scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TFRecordIO.scala
  scio-test/src/main/scala/com/spotify/scio/testing/BigtableMatchers.scala
  scio-test/src/main/scala/com/spotify/scio/testing/PipelineTestUtils.scala
  scio-test/src/test/scala/com/spotify/scio/testing/JobTestTest.scala
  scio-test/src/test/scala/com/spotify/scio/testing/SCollectionMatchersTest.scala
Labels: enhancement
